#include "app_board_monsoon.h"

void ESPFUNC app_board_monsoon_init() {
	gpio_init();

	GPIO_DIS_OUTPUT(BOOT_IO_FUNC);
	GPIO_DIS_OUTPUT(KEY_IO_FUNC);

	PIN_FUNC_SELECT(BOOT_IO_MUX, BOOT_IO_FUNC);
	PIN_FUNC_SELECT(KEY_IO_MUX, KEY_IO_FUNC);
	PIN_FUNC_SELECT(CTRL_IO_MUX, CTRL_IO_FUNC);
	PIN_FUNC_SELECT(LEDR_IO_MUX, LEDR_IO_FUNC);
	PIN_FUNC_SELECT(LEDG_IO_MUX, LEDG_IO_FUNC);

	GPIO_OUTPUT_SET(CTRL_IO_NUM, 0);
	ledr_off();
	ledg_off();
}